spring:
  datasource: #配置jdbc数据源
    url: jdbc:mysql://localhost:3306/power?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asiz/Shanghai&useSSL=false
    username: root
    userword: xwwfy
    druid:  # 可以是c3p0，dbcp或者druid、HikariCP等任意数据源
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter: # 这个过滤器的作用就是统计web应用请求中所有的数据库信息
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

  data:
    elasticsearch:
      repositories: # 开启Repository模式
        enabled: true
  elesticsearch:
    uris: localhost:9200

# 修改日志级别
logging:
  level:
    # 设置日志的默认级别为 info
    root: info
    # 设置com.example.poweradmin包下的日志级别是debug
    com.example.poweradmin: debug
  # 指定日志文件输出
  file:
    name: F:\java_project\mall\shevinfy_power_e-commerce\power e-commerce\document\log\poweradmin_log.txt

logstash:
  host: localhost
  enableInnerLog: false
