spring:
  datasource:
    url: jdbc:mysql://db:3306/power?useUnicode=ture&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: xwwfy

    druid:
      inttial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.jpg,*.png,*.gif,*.css,*.js,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
      uris: es:9200

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.example.power: info

logstash:
  host: logstash